language: python
python:
  - "3.6"
  - "3.6-dev"

install:
  - pip install -r requirements.txt
  - pip install -r optional_requirements.txt

script:
  - pytest 

notifications:
  email: frederike.duembgen@epfl.ch
